# The project version is the next release; untagged builds identify their source.
set(RF_BUILD_CHANNEL "development" CACHE STRING "development or stable")
set(RF_BUILD_NUMBER "local" CACHE STRING "CI run number, or local")
set(RF_BUILD_COMMIT "" CACHE STRING "Full source commit (passed into CI containers)")
set(RF_BUILD_DATE "" CACHE STRING "UTC build date")
find_package(Git QUIET)
if(NOT RF_BUILD_COMMIT AND Git_FOUND)
    execute_process(COMMAND "${GIT_EXECUTABLE}" rev-parse HEAD
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}" OUTPUT_VARIABLE RF_BUILD_COMMIT
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
endif()
if(NOT RF_BUILD_COMMIT)
    set(RF_BUILD_COMMIT "unknown")
endif()
string(LENGTH "${RF_BUILD_COMMIT}" commit_length)
if(NOT RF_BUILD_COMMIT STREQUAL "unknown" AND
   (NOT RF_BUILD_COMMIT MATCHES "^[0-9a-f]+$" OR
    (NOT commit_length EQUAL 40 AND NOT commit_length EQUAL 64)))
    message(FATAL_ERROR "RF_BUILD_COMMIT must be a full Git commit hash")
endif()
if(NOT RF_BUILD_NUMBER MATCHES "^(local|[1-9][0-9]*)$")
    message(FATAL_ERROR "RF_BUILD_NUMBER must be a positive CI run number or local")
endif()
if(NOT DEFINED RF_BUILD_DIRTY)
    set(RF_BUILD_DIRTY OFF)
    if(Git_FOUND AND RF_BUILD_NUMBER STREQUAL "local")
        execute_process(COMMAND "${GIT_EXECUTABLE}" status --porcelain
            WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}" OUTPUT_VARIABLE dirty ERROR_QUIET)
        if(dirty)
            set(RF_BUILD_DIRTY ON)
        endif()
    endif()
endif()
if(RF_BUILD_CHANNEL STREQUAL "stable")
    set(RF_VERSION "${PROJECT_VERSION}")
elseif(RF_BUILD_CHANNEL STREQUAL "development")
    string(SUBSTRING "${RF_BUILD_COMMIT}" 0 7 short_commit)
    set(RF_VERSION "${PROJECT_VERSION}-dev.${RF_BUILD_NUMBER}.g${short_commit}")
    if(RF_BUILD_NUMBER STREQUAL "local" AND RF_BUILD_DIRTY)
        string(APPEND RF_VERSION ".dirty")
    endif()
else()
    message(FATAL_ERROR "RF_BUILD_CHANNEL must be development or stable")
endif()
if(NOT RF_BUILD_DATE)
    string(TIMESTAMP RF_BUILD_DATE "%Y-%m-%dT%H:%M:%SZ" UTC)
endif()
if(NOT RF_BUILD_DATE MATCHES "^[0-9-]+T[0-9:]+Z$")
    message(FATAL_ERROR "RF_BUILD_DATE must be a UTC ISO date")
endif()
configure_file("${CMAKE_CURRENT_LIST_DIR}/BuildInfo.json.in"
    "${CMAKE_BINARY_DIR}/BUILD-INFO.json" @ONLY)
message(STATUS "CroccoSpectrum build version: ${RF_VERSION}")
